### ISSUE TITLE
Pydicom and Pynetdicom

### ISSUE THREAD

**Issue by keldnorman** [zerstoeren/dicom-scan#1]
root@admin:~/Development/Dicom-Scan/dicom-scan# ./dicomscanner.py -ip x,x,x,x 104
Traceback (most recent call last):
  File "./dicomscanner.py", line 13, in <module>
    from pynetdicom3 import AE
ImportError: No module named pynetdicom3

root@admin:~/Development/Dicom-Scan/dicom-scan# ./dicomscanner3.py -ip x.x.x.x 104
Traceback (most recent call last):
  File "./dicomscanner3.py", line 13, in <module>
    from pynetdicom3 import AE
ImportError: No module named pynetdicom3

I have git cloned both pynetdicom and pydicom repos and installed them
gir clone https://github.com/pydicom/pydicom.git
cd pydicom
python ./setup.py install

git clone https://github.com/scaramallion/pynetdicom3.git
cd pynetdicom
python ./setup.py install

Do you have a tip to get that include to work ?

**Comment by keldnorman** [comment]
I fixed it.. removed the "3" in the includes and included everything from pydicom and pynetdicom:

...
from socket import *
from pydicom import *
from pynetdicom import AE

**Comment by zerstoeren** [comment]
That is good to know.  Thank you.  I will reference that in the documentation as well with a "kudos" to you as soon as I finish this paid project I am working on which should be finishing up in a few weeks.  I plan to get back to working on and adding the other DICOM commands at that time and then adding PACS.
